// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnvxmfgflzhvtuunysxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudnhtZmdmbHpodnR1dW55c3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDcwODcsImV4cCI6MjA2MDgyMzA4N30.QTWdCPhksvKQKAcQsp31dHB9_NQMzyePjd3RiiVtgaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);